name: branch workflow

on:
  push:
    # Only run on the master branch.
    branches: [master]
  create:
  delete:  

jobs:
  master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event.ref_type != 'branch'
    env:
      ENVIRONMENT_NAME: prod
    steps: 
      - name: deploy application to production
        run: |
          echo "kubectl create -n ${ENVIRONMENT_NAME}"      

  branch:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: github.event.ref
    steps: 
      - name: deploy application to new branch
        if: github.event_name == 'create'
        run: |
          echo "kubectl create -n ${ENVIRONMENT_NAME}"    

      - name: Delete application from removed branch
        if: github.event_name == 'delete'
        run: |
          echo "kubectl delete all --all -n ${ENVIRONMENT_NAME}"
          