### Used to split workflow because of potential dependabot vulnerability
### See https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544

name: Dependabot PR Check
on:
  pull_request

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
